# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{httphere}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Parker"]
  s.date = %q{2010-02-10}
  s.default_executable = %q{httphere}
  s.description = %q{httphere is a very small and simple ruby command-line HTTP file server.}
  s.email = %q{gems@behindlogic.com}
  s.executables = ["httphere"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/httphere",
     "httphere.gemspec",
     "lib/httphere/markdown.rb",
     "lib/httphere/textile.rb"
  ]
  s.homepage = %q{http://dcparker.github.com/httphere}
  s.post_install_message = %q{
[34mhttphere wants to detect MIME-types! For this
you'll need to install the open-source shared-mime-info.
Assuming you're on a Mac, you can simply run:
[0m  [31msudo port install shared-mime-info[0m

 * This gem has not been tested on Windows.

}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple Ruby HTTP file server}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<shared-mime-info>, [">= 0"])
      s.add_runtime_dependency(%q<chardet>, [">= 0"])
    else
      s.add_dependency(%q<shared-mime-info>, [">= 0"])
      s.add_dependency(%q<chardet>, [">= 0"])
    end
  else
    s.add_dependency(%q<shared-mime-info>, [">= 0"])
    s.add_dependency(%q<chardet>, [">= 0"])
  end
end

